### ISSUE TITLE
checkExchange: unhandled error

### ISSUE THREAD

**Issue by mathiaske** [squaremo/amqp.node#108]
Sorry for bothering you with probably such a trivial matter, but slowly I'm running out of ideas
I'm kind a new to the whole callback hell and promises thing (sounds quite interesting).

I'm trying to check if a certain rabbitMQ exchange already exists using the function checkExchange
Whatever I do or try I get an unhandled error message that I don't manage to catch in the promises API; with the callback API I at least manage to catch the error, kill the process but cannot really resolve it (i.e. open new connection and create the missing exchange).
Is this now because I'm simply screwing something up or because the checkExchange function breaks the channel?

PS: The plan is that at a later point I can create the required rabbitMQ elements (exchanges, queues, bindings etc) from within our application.

``` javascript
function createExchange(exchange)
{
  amqp.connect(mq_protocol+mq_user+":"+mq_userPW+"@"+mq_host+":"+mq_port+'/'+mq_vhost)
  .then(function(connection)
  {
    var ok = connection.createChannel().then(function(channel)
    {
      console.log('checking exchange');
      channel.checkExchange(exchange)
      .then(function()
      {
        console.log('found exchange, be happy');
      })
      .catch(function()
      {
        console.log('not so happy');
      })
    })
    return ok;
  }).then(null, console.log);
}
```

```
checking exchange
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'testexchange' in vhost 'test'"
    at Channel.C.accept (/home/xxx/node_modules/amqplib/lib/channel.js:399:24)
    at Connection.mainAccept [as accept] (/home/xxx/node_modules/amqplib/lib/connection.js:62:33)
    at Socket.go (/home/xxx/node_modules/amqplib/lib/connection.js:459:48)
    at Socket.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:423:10)
    at emitReadable (_stream_readable.js:417:7)
    at readableAddChunk (_stream_readable.js:173:11)
    at Socket.Readable.push (_stream_readable.js:125:10)
    at TCP.onread (net.js:514:20)
```

**Comment by PritamUpadhyay** [comment]
This is how I found my workaround.
===========================
```javascript
function createExchange(exchange)
{
  amqp.connect(mq_protocol+mq_user+":"+mq_userPW+"@"+mq_host+":"+mq_port+'/'+mq_vhost)
  .then(function(connection)
  {
    var ok = connection.createChannel().then(function(channel)
    {
     channel.on('error', function (err) {
            console.log('channel Closed');
        });
      console.log('checking exchange');
      channel.checkExchange(exchange)
      .then(function()
      {
        console.log('found exchange, be happy');
      })
      .catch(function()
      {
        console.log('not so happy');
        var newChannel = conn.createChannel().then(function (Newchnnel) {                
                    Newchnnel.assertExchange(exchange, 'topic', { autoDelete: false, durable: true, passive: true });                   
                });
      })
    })
    return ok;
  }).then(null, console.log);
}
