### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by IgorDePaula** [squaremo/amqp.node#193]
I received this error on use the delay queue rabbitmq plugin. I do not know do about this error.
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Connection closed: 541 (INTERNAL-ERROR) with message "INTERNAL_ERROR"
    at Object.accept (/home/igor/nodes/testsMQ/node_modules/amqplib/lib/connection.js:89:32)
    at Connection.mainAccept [as accept] (/home/igor/nodes/testsMQ/node_modules/amqplib/lib/connection.js:62:33)
    at Socket.go (/home/igor/nodes/testsMQ/node_modules/amqplib/lib/connection.js:465:48)
    at Socket.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by IgorDePaula** [comment]
I tested this code

https://gist.github.com/diegodfsd/33b8efc699ff86206181

**Comment by squaremo** [comment]
I installed the plugin (for RabbitMQ 3.5.3) and ran the code in the gist, and it worked OK. I wonder if RabbitMQ itself ran into a problem -- anything in the rabbitmq logs?

**Comment by IgorDePaula** [comment]
I used an  ubuntu 14.04 vagrant image with rabbitmq 3.2.4 (installed from official repository), with node.js 0.12.7, amqplib 0.4.0 and I receive this same error.

**Comment by IgorDePaula** [comment]
I tested too with rabbitmq 3.4.3, script of tutorials is normal, but the script above occurred the cited error.

**Comment by IgorDePaula** [comment]
Ok, I tested now with rabbitmq 3.5.6 and works fine, thank you.
