### ISSUE TITLE
Support Auto-reconnection

### ISSUE THREAD

**Issue by skeggse** [squaremo/amqp.node#25]
At the moment, when a socket closes it's basically permanent. All kinds of methods are replaced in favor of functions which only `throw` and there's no reconnect support.

Even in a data center, connections can fail or time out, and reconnection would allow the connection to fail and recover from the failure, instead of simply giving up.

This might need to happen at the `connect.js` level given the current setup, but that would put messages that have been sent but not acked into an uncertain place where it's unclear if the message has reached the server or just fallen. I know from experience that trying to get reconnection to work well can be tricky. For a counterexample, see `node-amqp`'s reconnection, which appears to leak everywhere.

**Comment by richzw** [comment]
I am not familiar with CoffeeScript, and I try to convert this [https://gist.github.com/benmoss/e93125d1fb3561be9276](https://gist.github.com/benmoss/e93125d1fb3561be9276 ) 

to Javascript here [https://gist.github.com/richzw/57177f3fecbeb921819c](https://gist.github.com/richzw/57177f3fecbeb921819c)

However, there is one error `[ReferenceError: connect_ is not defined]`

@squaremo or @benmoss , could you please help me to figure out the failure reason? Thanks in advance.

**Comment by richzw** [comment]
I am not familiar with CoffeeScript, so I try to convert the [https://gist.github.com/benmoss/e93125d1fb3561be9276](https://gist.github.com/benmoss/e93125d1fb3561be9276) to JavaScript.

Here it is [https://gist.github.com/richzw/57177f3fecbeb921819c](https://gist.github.com/richzw/57177f3fecbeb921819c)

@squaremo and @benmoss, Could you please help me review it? Thanks in advance.

I want to know what does the `createFakeChannel_ ` function mean?

**Comment by cmoesel** [comment]
@richzw, coffeescript compiles into javascript, so if you need javascript, you don't need to manually convert it-- you can just take the result of compiling the coffeescript.  Here is the result of the coffeescript you referenced above: http://pastebin.com/REPR1zP2

**Comment by benmoss** [comment]
@richzw the `createFakeChannel` function was there so that if `publish` is called while the server is disconnected it will be a no-op, rather than throwing an exception. It allows the other parts of the program to work while just dropping messages instead of sending them to RabbitMQ. This may not be acceptable for all programs, but it worked well enough for mine.

**Comment by richzw** [comment]
@cmoesel and @benmoss thanks for your help.

@benmoss, I want to publish message to amqp once the channel is ok, otherwise, continue to reconnect to amqp. so

	when(amqp.connect( this.addr_ ))
		.with( this )
		.then( this.createChannel_ )
		.then( this.createExchange_ )
		.then( this.handleUnrouteableMessages_ )
		.then( this.handleDisconnections_ )
		.catch( this.reconnect_ )
		.done( this.publish_ ); 

But it seems the above codes is not working well. Even if the connection failed, it continue to publish message to amqp.

In your codes, could you please tell me how to call `publish` correctly?

**Comment by benmoss** [comment]
@richzw yeah, just create an instance of the MessageBus in your app startup and use it as a global object. i've seen this done by having a `globals` module that has all the global objects. wherever you need to publish from the rest of your app:

```javascript
module.exports = {
  messageBus: new MessageBus()
};
```

```javascript
var messageBus = require("globals").messageBus;

messageBus.publish("order.created", {orderNumber: 555});
```

**Comment by richzw** [comment]
hi @benmoss  and @squaremo 

In this gist [https://gist.github.com/richzw/6b4d348c6b8abdc8176e](https://gist.github.com/richzw/6b4d348c6b8abdc8176e), I want to `Sender` class to handle connection failure recover through re-connection. Here are the test codes.

```javascript
var Sender = require('./sender.js');
var sender = new Sender( amqpAddress, 3000);

function sendMessage( key, msg ) {
	var byteBuffer = msg.encode().toBuffer();
	sender.deliverMessage( key, byteBuffer );
}

// send message every 5 seconds
var CronJob = require('cron').CronJob;
var send_message_job = new CronJob({
	cronTime: '*/5 * * * * *',
	onTick: function(){
		sendMessage( key, message );
	},
	start: true,
});

send_message_job.start();
```

Then I try to stop and start `amqp` service randomly. And the failure recover can be well handled, but it can failed with errors

`Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)`

Can anyone help me figure out how to handle it?

**Comment by benmoss** [comment]
@richzw sorry I can't help you

**Comment by jwalton** [comment]
Ok, I've taken a stab at fixing this whole reconnection problem.  Check out https://github.com/benbria/node-amqp-connection-manager and see if it solves your use case.  If it doesn't, or if you have suggestions, I'm certainly interested in hearing about it.  :)

**Comment by firemyst13** [comment]
Is there something horribly wrong with what I've done here, in regards to re-establishing a connection?  It seems to work to reconnect to the server (I've been starting/stopping it for testing...)

```javascript
function connectRMQ() {
  amqp.connect(config.rabbitmq.URI).then(function(conn) {
    conn.on('close', function() {
      console.error('Lost connection to RMQ.  Reconnecting in 60 seconds...');
      return setTimeout(connectRMQ, 60 * 1000);
    });
    return conn.createChannel().then(function(ch) {
        var ok = ch.assertQueue(config.rabbitmq.queue, {durable: true});
        ok = ok.then(function() {
            ch.prefetch(1);
            ch.consume(config.rabbitmq.queue, doWork, {noAck: false});
        });
        return ok.then(function() {
            console.log(" [*] Waiting in %s.", config.rabbitmq.queue);
        });

        function doWork(msg) {
            var body = msg.content.toString();
            console.log(" [x] Received %s", body);
            setTimeout(function() {
                ch.ack(msg);
            }, config.rabbitmq.timeout);
        }
    });
  }).then(null, function() {
     setTimeout(connectRMQ, 10 * 1000);
     return console.log('connection failed');
  });
}

connectRMQ();
```

**Comment by luoyjx** [comment]
my implemention.

```
function MQ() {
	this.connection = null;
	this.init();
}

/**
 * init
 * @return {[type]} [description]
 */
MQ.prototype.init = function init() {
	var self = this;

	Connection
		.createConnection(config.rabbitMQ_url)
		.then(function (conn) {

			self.connection = conn;

			conn.on('error', function(err) {
				log.error('[mq] connection error ', err);
				self.reconnect();
			});

			log.info('[mq] create connection success');

			return Channel
				.createChannel(conn);
		})
		.then(function (ch) {

			process.once('SIGINT', function() { 
				log.info('kill by signal SIGINT');
				ch.close();
				self.connection.close(); 
				self.connection = null;
				process.exit(0);
			});

			ch.on('error', function(error) {
				// ch.close();
				log.error('[mq] channel error: ', error);
			});

			log.info('[mq] create channel success');

			return Exchange
				.assertExchange(ch, config.exchange_name, ExchangeTypes.DIRECT, {durable: false})
				.then(function () {
					log.info('[mq] assert exchange [%s] [%s]', config.exchange_name, ExchangeTypes.DIRECT);

					return Queue
						.assertQueue(ch, QUEUE_NAME, {exclusive: false, durable: false}); 
				})
				.then(function (queue) {
					log.info('[mq] assert queue [%s] success', QUEUE_NAME);

					log.debug(queue);

					// bind to exchange
					return Queue.
						bindQueue(ch, QUEUE_NAME, config.exchange_name, ROUTE_KEY);
				})
				.then(function() {
					log.info('[mq] bind queue [%s] to exchange [%s]', QUEUE_NAME, config.exchange_name);

					return Consume
						.consume(self.connection, ch, QUEUE_NAME);
				})
		})
		.catch(function (err) {
			log.error('[mq] Init failed , error: ', err);
			self.reconnect();
		});
};

/**
 * reconnect
 * @return {[type]} [description]
 */
MQ.prototype.reconnect = function() {
	var self = this;

	log.info('[mq] try reconnect 3 seconds later');

	setTimeout(function () {
		self.init();
		self.reconnectCount++;
	}, 3000);	
}
```

**Comment by magicdawn** [comment]
Ha, just see ioredis Redis client do connection recover stuff well
https://github.com/luin/ioredis#auto-reconnect

code
https://github.com/luin/ioredis/blob/v2.5.0/lib/redis/event_handler.js#L62-L103

**Comment by dskrvk** [comment]
In my experience we have to listen to both the `error` and the `close` events. I tried listening to only one event type, but each one only covers some of the situations:
1. When rabbitmq is stopped, the client emits an `error` event.
2. When rabbitmq forcefully terminates the connection, a `close` event is emitted.

I went ahead and subscribed to both, however, now in situation 1 **both** events are emitted, and if we're not careful we'll end up reconnecting twice, which eventually leads to `PRECONDITION_FAILED - unknown delivery tag` errors (see https://github.com/squaremo/amqp.node/issues/271#issuecomment-243795316). The below implementation takes this into account.

```javascript
function connect(onMessage, attempt = 0) {
    let reconnecting = false;

    function _onConnectionError(err) {
        if (reconnecting) {
            return Promise.resolve();
        }
        reconnecting = true;
        const nextDelay = nextExponentialDelay(attempt, MAX_DELAY, DELAY_STEP, DELAY_RATE);
        logger.error(`AMQP channel error, retrying in ${nextDelay} s`, err);
        return new Promise(resolve => setTimeout(() => connect(onMessage, attempt + 1).then(resolve), nextDelay * 1000));
    }

    return mq.connect(amqpConn).then(connection => {
        return connection.createChannel().then(channel => {
            // recreate the exchange/queue topology as needed, then:
            attempt = 0;
            reconnecting = false;
            connection.once("close", _onConnectionError);
            connection.once("error", _onConnectionError);
            logger.info("Waiting for messages");
            return channel;
        });
    }).catch(_onConnectionError);
}
```

**Comment by bmxpiku** [comment]
``> In my experience we have to listen to both the `error` and the `close` events. I tried listening to only one event type, but each one only covers some of the situations:
> 
> 1. When rabbitmq is stopped, the client emits an `error` event.
> 2. When rabbitmq forcefully terminates the connection, a `close` event is emitted.
> 
> I went ahead and subscribed to both, however, now in situation 1 **both** events are emitted, and if we're not careful we'll end up reconnecting twice, which eventually leads to `PRECONDITION_FAILED - unknown delivery tag` errors (see [#271 (comment)](https://github.com/amqp-node/amqplib/issues/271#issuecomment-243795316)). The below implementation takes this into account.
> 
> ```js
> function connect(onMessage, attempt = 0) {
>     let reconnecting = false;
> 
>     function _onConnectionError(err) {
>         if (reconnecting) {
>             return Promise.resolve();
>         }
>         reconnecting = true;
>         const nextDelay = nextExponentialDelay(attempt, MAX_DELAY, DELAY_STEP, DELAY_RATE);
>         logger.error(`AMQP channel error, retrying in ${nextDelay} s`, err);
>         return new Promise(resolve => setTimeout(() => connect(onMessage, attempt + 1).then(resolve), nextDelay * 1000));
>     }
> 
>     return mq.connect(amqpConn).then(connection => {
>         return connection.createChannel().then(channel => {
>             // recreate the exchange/queue topology as needed, then:
>             attempt = 0;
>             reconnecting = false;
>             connection.once("close", _onConnectionError);
>             connection.once("error", _onConnectionError);
>             logger.info("Waiting for messages");
>             return channel;
>         });
>     }).catch(_onConnectionError);
> }
> ```

it works nice, one thing to add would be some condition to break, in case you wont like infinite restart loop
```
export const connect = async (attempt = 1): Promise<void> => {
  let reconnecting = false;

  if (attempt === 10) {
    throw new RabbitMQError('Maximum reconnect attempts exceeded.');
  }
  
  async function onConnectionError(err): Promise<void> {
    connection = null;
    if (reconnecting) {
      return Promise.resolve();
    }
    reconnecting = true;
    logger.error(`AMQP channel error, retrying in ${attempt} s`, err);
    await setTimeout(attempt * 1000);
    return connect(attempt + 1);
  }

  try {
    connection = await amqp.connect(RABBITMQ_URL);
    if (connection) {
      logger.info('AMPQ client connected');
      connection.once('error', onConnectionError);
      connection.once('close', onConnectionError);
      reconnecting = false;
    }
  } catch (e) {
    await onConnectionError(e);
  }
};
```

**Comment by devthejo** [comment]
Here is my workaround:

```js
class ReconnectableProxy {
  constructor(target) {
    this.target = target
    this.callLog = []
    this.proxy = new Proxy({}, this.createHandler())
  }

  createHandler() {
    return {
      get: (obj, prop) => {
        if (typeof this.target[prop] === "function") {
          return (...args) => {
            this.callLog.push({ method: prop, args })
            return this.target[prop](...args)
          }
        }
        return this.target[prop]
      },
    }
  }

  setTarget(newTarget) {
    this.target = newTarget
  }

  async reconnect(newTarget) {
    this.target = newTarget
    await this.replayCalls()
  }

  async replayCalls() {
    for (const { method, args } of this.callLog) {
      await this.target[method](...args)
    }
  }

  getProxy() {
    return this.proxy
  }
}

const proxyManager = new ReconnectableProxy()
let reconnecting = false
const createConnection = async () => {
  const onConnectionError = async () => {
    if (reconnecting) {
      return
    }
    reconnecting = true
    await yaRetry(
      async (_bail) => {
        logger.debug("rabbitmq disconnected, trying to reconnect")
        const conn = await createConnection()
        await proxyManager.reconnect(conn)
        logger.debug("reconnected")
      },
      {
        retries: 10,
        minTimeout: 1000,
        maxTimeout: 30000,
        ...(autoReconnect.retryOptions || {}),
      }
    )
    reconnecting = false
  }
  const conn = await amqplib.connect(amqpURL)
  conn.once("close", onConnectionError)
  conn.once("error", onConnectionError)
  return conn
}

const conn = await createConnection()
proxyManager.setTarget(conn)
const connProxy = proxyManager.getProxy()

// then use connProxy in the code instead of conn
```
imlpemented here: https://codeberg.org/devthefuture/modjo/src/branch/master/plugins/amqp/index.js
it will work great if you have fixed channels, and you want to re-sub on reconnect, but doesn't work well in case you do many dynamic sub and unsub
it suitable for a "classic" queue worker

**Comment by cressie176** [comment]
@devthejo 

A couple of things to watch out for...

```js
  conn.once("error", onConnectionError)
```

You can get two error events. Because once will remove the error handler after the first, the second will be unhandled and can crash your application.

**Comment by devthejo** [comment]
thanks @cressie176 for pointing this, I'm just realizing it now and I'm trying to find a better implementation, I will edit my post when it will be done

**Comment by Tsimopak** [comment]
Any update on this one? Will it be implemented? seems like a 10year feature request

**Comment by michaelklishin** [comment]
@Tsimopak you are welcome to contribute it. This is open source software after all. Asking others to implement a feature you need is not how open source software advanced.

**Comment by michaelklishin** [comment]
There are several clients to not just derive inspiration from but more or less copy the algorithm.

Bunny (a Ruby client) and RabbitMQ Java client were the first ones to implement connection
recovery back in 2012-2013, and what they do (and intentionally do not try to do) during recovery is [documented](https://www.rabbitmq.com/client-libraries/java-api-guide#recovery) and very widely battle tested by now.

So instead of complaining that "there are 10 year old feature requests", how about those who badly need this feature contribute it by copying the general idea from the Java or Ruby clients, and adapting to be close to what a JavaScript user would expect.

Every important decision around connection recovery has already been made and battle-tested over a decade. I have implemented connection recovery in the first three clients that have gotten it and in my opinion, that's a good third if not half of the work already done.

**Comment by michaelklishin** [comment]
@cressie176 alternatively, this client can document how to implement connection recovery in the application code and decide not to provide it.

[Pika](https://github.com/pika/pika?tab=readme-ov-file#connection-recovery) (a Python client) and the [Go AMQP 0-9-1 client](https://github.com/rabbitmq/amqp091-go/blob/main/_examples/client/client.go#L123-L150) do just that. I personally prefer the approach of other clients but it works reasonably well for Python and Go users.

**Comment by cressie176** [comment]
Hi @Tsimopak, Hi @michaelklishin,

> Any update on this one? Will it be implemented? seems like a 10year feature request

It's a fair point, and really my fault for not making a decision and communicated it clearly.

I have no plans to implement auto-reconnection in this library. I would consider a PR, but it would have to be configurable, well tested, well documented and follow an established approach such as that taken by [the java client](https://www.rabbitmq.com/client-libraries/java-api-guide#connection-recovery). 

I will add keep this ticket open to remind me to add an example of how to do connection recovery. In the meantime you could use / borrow from https://www.npmjs.com/package/rascal or https://www.npmjs.com/package/amqp-connection-manager.
