### ISSUE TITLE
TypeError: Cannot read property 'publish' of undefined

### ISSUE THREAD

**Issue by mitchellporter** [squaremo/amqp.node#292]
I am using a library called [Jackrabbit](https://github.com/hunterloftis/jackrabbit) that uses `amqp.node`. I opened an issue for this on `jackrabbit's` repo but the library is very inactive at this point so I thought I'd try here. I'm also posting here because for all I know this issue has nothing to do with `jackrabbit` and is happening because of something with `amqp.node`

Here is the original issue I posted, but modified based on additional testing and information that I've gathered:

I have a clock process running on `Heroku` and I keep getting the following error every 20 minutes exactly: `TypeError: Cannot read property 'publish' of undefined`

Here's the stack trace:
```
 /app/node_modules/jackrabbit/lib/exchange.js:128
app[clock.1]:       var drained = channel.publish(emitter.name, opts.key, new Buffer(msg), opts);
app[clock.1]:                            ^
app[clock.1]: 
app[clock.1]: TypeError: Cannot read property 'publish' of undefined
app[clock.1]:     at sendMessage (/app/node_modules/jackrabbit/lib/exchange.js:128:28)
app[clock.1]:     at EventEmitter.publish (/app/node_modules/jackrabbit/lib/exchange.js:114:16)
app[clock.1]:     at CronJob.sortLiveBroadcasts (/app/lib/clock.js:38:14)
app[clock.1]:     at CronJob.fireOnTick (/app/node_modules/cron/lib/cron.js:392:22)
app[clock.1]:     at Timeout.callbackWrapper [as _onTimeout] (/app/node_modules/cron/lib/cron.js:435:9)
app[clock.1]:     at tryOnTimeout (timers.js:224:11)
app[clock.1]:     at Timer.listOnTimeout (timers.js:198:5)
```

The error is thrown, the server crashes, the server automatically restarts on `Heroku`, and then it runs fine for another 20 minutes and then the error is thrown again. This cycle has been repeating itself for the past few days.

Here is the code for my entire `clock.js` file:

```
var config = require('./server/config/config');
var logger = require('./logger');
var CronJob = require('cron').CronJob;
var rabbit = require('jackrabbit')(config.rabbit_url);
var exchange = rabbit.default();

var SORT_LIVE_FEED_QUEUE = config.SORT_LIVE_FEED_QUEUE;
var SORT_VOD_FEED_QUEUE = config.SORT_VOD_FEED_QUEUE;

var sortLiveBroadcastsJob = new CronJob('*/10 * * * * *', sortLiveBroadcasts, null, false, 'America/Los_Angeles');
var sortVODBroadcastsJob = new CronJob('*/15 * * * * *', sortVODBroadcasts, null, false, 'America/Los_Angeles');

sortLiveBroadcastsJob.start();
sortVODBroadcastsJob.start();

// Graceful shutdown
var gracefulShutdown = function() {
    sortLiveBroadcastsJob.stop();
    sortVODBroadcastsJob.stop();
    rabbit.close();
}

process.on('SIGTERM', gracefulShutdown);

function sortLiveBroadcasts() {
    
    // Publish message to queue
    exchange.queue({ name: SORT_LIVE_FEED_QUEUE, durable: true });
    exchange.publish({ status: 'live' }, { key: SORT_LIVE_FEED_QUEUE });
}

function sortVODBroadcasts() {
    
    // Publish message to queue
    exchange.queue({ name: SORT_VOD_FEED_QUEUE, durable: true });
    exchange.publish({ status: 'vod' }, { key: SORT_VOD_FEED_QUEUE });
}
```

**Comment by cressie176** [comment]
I'm not familiar with jackrabbit but after looking at exchange.js I'd guess something is calling ```bail``` and [setting the channel to undefined](https://github.com/hunterloftis/jackrabbit/blob/master/lib/exchange.js#L146)

By next guess is that it's some kind of network error (or heartbeat timeout) which is causing amqp to close the connection and therefore channel. jackrabbit [binds bail to the channel 'close'](https://github.com/hunterloftis/jackrabbit/blob/master/lib/exchange.js#L162) event.

I would fork the jackrabbit project, add some debug, redeploy and see what you get.
