### ISSUE TITLE
Error when closing channel in 0.5.0

### ISSUE THREAD

**Issue by dmcquay** [squaremo/amqp.node#301]
When I try to close a channel directly, I get the following error:

```
Unhandled rejection TypeError: Cannot read property 'closeBecause' of undefined
at /home/dev/repos/ps-messaging-node/node_modules/amqplib/lib/channel_model.js:77:16
at tryCatcher (/home/dev/repos/ps-messaging-node/node_modules/bluebird/js/release/util.js:16:23)
at Function.Promise.fromNode.Promise.fromCallback (/home/dev/repos/ps-messaging-node/node_modules/bluebird/js/release/promise.js:179:30)
at Channel.C.close (/home/dev/repos/ps-messaging-node/node_modules/amqplib/lib/channel_model.js:76:18)
at Timeout.setTimeout (/home/dev/repos/ps-messaging-node/test.js:33:15)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at Timer.listOnTimeout (timers.js:207:5)
```

If I close the connection only, it works fine. Here is code to reproduce the error. As far as I can tell, calling connection.close will suit my needs, but the docs indicate that channel.close should still work, so I thought you might want to fix that.

```javascript
'use strict'

const amqp = require('amqplib')

const username = 'guest'
const password = 'guest'
const host = 'localhost'
const queueName = 'test'

const amqpUrl = `amqp://${username}:${password}@${host}`

let conn, channel

amqp.connect(amqpUrl)
  .then(_conn => {
    conn = _conn
    return conn.createChannel()
  })
  .then(_channel => {
    channel = _channel
    channel.consume(queueName, (message) => {
      console.log('got a message', message)
    })

    setTimeout(() => {
      console.log('closing')

      // this works fine
      // conn.close()
      //   .then(() => console.log('done closing'))

      // this causes an error
      channel.close()
        .then(() => conn.close())
        .then(() => console.log('done closing'))
    }, 200)
  })
```

**Comment by ismriv** [comment]
I'm reproducing the same issue. Going back to 0.4.x for the time being...

**Comment by nfantone** [comment]
This was already [reported](https://github.com/squaremo/amqp.node/issues/297) and [fixed](https://github.com/squaremo/amqp.node/pull/298). It's still unreleased, though.

Please, search before opening a new issue.

**Comment by dmcquay** [comment]
Closing per nfantone's comment.
