### ISSUE TITLE
ERROR: unable to verify the first certificate

### ISSUE THREAD

**Issue by igorissen** [squaremo/amqp.node#331]
Hi,

Trying to connect to a RabbitMQ server on a service called [Compose.com](https://compose.com) and I keep getting this error message:

```
Error: unable to verify the first certificate
        at Error (native)
        at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
        at emitNone (events.js:86:13)
        at TLSSocket.emit (events.js:185:7)
        at TLSSocket._finishInit (_tls_wrap.js:603:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```

This an example of the connection string that Compose give me

```
amqps://[username]:[password]@portal.example.com:11111/vhostname
```

You can see that on each examples you use `amqp://`. Is the module handle the secure version of the protocol `amqps://` ?

And you can find [here](https://gist.github.com/igorissen/c3e8db8ba7822c7ed54c6a269483560e) the module created to handle connection and a few methods.

Any idea how to fix that ?

Thank you.

**Comment by igorissen** [comment]
Found a solution with the help of Compose helpdesk using [this](https://help.compose.com/docs/rabbitmq-connecting-to-rabbitmq#section-node-and-rabbitmq).

```js
const url = require('url');

const uri = 'amqp://localhost' // or amqps://.........
const parsedURI = url.parse(uri);

amqp.connect(uri, { servername: parsedURI.hostname })
```

Works with `amqp://` and `amqps://`.

You can check [my code](https://gist.github.com/igorissen/c3e8db8ba7822c7ed54c6a269483560e) for the changes

**Comment by squaremo** [comment]
@diogosantosmendes Did the solution work for you? It's been reported as not working (any more), elsewhere (#371).

**Comment by salimakhtar92** [comment]
I am getting following erroe

```
Exception while invoking method 'serverLogin' Error: unable to verify the first certificate
I20180812-22:11:35.569(5.5)?     at Object.Future.wait (/home/salim/.meteor/packages/meteor-tool/.1.4.3_1.1k6vv31.onjf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20180812-22:11:35.570(5.5)?     at Object.call (packages/meteor.js:213:24)
I20180812-22:11:35.570(5.5)?     at [object Object].Meteor.methods.serverLogin (imports/accounts/api/loginmethod.js:8:15)
I20180812-22:11:35.571(5.5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20180812-22:11:35.571(5.5)?     at packages/ddp-server/livedata_server.js:719:19
I20180812-22:11:35.572(5.5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20180812-22:11:35.572(5.5)?     at packages/ddp-server/livedata_server.js:717:40
I20180812-22:11:35.572(5.5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20180812-22:11:35.573(5.5)?     at packages/ddp-server/livedata_server.js:715:46
I20180812-22:11:35.573(5.5)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
I20180812-22:11:35.574(5.5)?     - - - - -
I20180812-22:11:35.574(5.5)?     at Error (native)
I20180812-22:11:35.574(5.5)?     at TLSSocket.<anonymous> (_tls_wrap.js:1039:38)
I20180812-22:11:35.575(5.5)?     at emitNone (events.js:67:13)
I20180812-22:11:35.575(5.5)?     at TLSSocket.emit (events.js:166:7)
I20180812-22:11:35.575(5.5)?     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:603:8)
I20180812-22:11:35.576(5.5)?     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:445:38)

```
My method:
```
import { Meteor } from 'meteor/meteor';

Meteor.methods({
	'serverLogin': function(email, password){
		
		let path =`https://www.XYZ.com/login/token/${email}/${password}`;
		return HTTP.call('GET', path);
	},
});
```
