### ISSUE TITLE
connection.close causes process to die and error is uncatchable

### ISSUE THREAD

**Issue by mateodelnorte** [squaremo/amqp.node#334]
Hi there. This is in response to a reported error in servicebus, which uses amqplib (https://github.com/mateodelnorte/servicebus/issues/93). 

Issue: Exiting RabbitMQ causes client code to exit without error. connection.close does fire, but subsequently throwing or emitting an error is somehow swallowed. 

This behavior is showing up in servicebus, and it looks like it may be related to the promise library in amqplib. For both of the following examples (throwing uncaught error and emitting unhandled error), both applications will crash with no uncaught exception or unhandled rejection. I'd expect one of the two. 
```
var amqp = require('amqplib');
var EventEmitter = require('events').EventEmitter;

amqp.connect('amqp://localhost').then(function (conn) {
  conn.on('close', function (event) {
    console.log('we get our event here', event)
    if (require('amqplib/lib/connection').isFatalError(event.Error)){
      console.log('and its fatal, but throwing seems to be swallowed - perhaps by the when.defer() promise?')
      throw new Error(event)
      console.log('something is catching this, eating it, and causing the process to die')
    }
  });
}).catch(function (err) {
  console.log('no error here either', err);
}).then(null, function(err) {
  console.log('no error here', err);
});

process.on('uncaughtException', function (exception) {
  console.log('no uncaught exception', exception);
});

process.on('unhandledRejection', (reason, p) => {
  console.log('no unhandled rejection at: Promise', p, 'reason:', reason);
});
```
```
class Wat extends EventEmitter {
  constructor () {
    super();

    var self = this;

    amqp.connect('amqp://localhost').then((conn) => {
      conn.on('close', function (event) {
        console.log('we get our event here', event)
        if (require('amqplib/lib/connection').isFatalError(event.Error)){
          console.log('and its fatal, but emitting error seems to be swallowed - perhaps by the when.defer() promise?')
          self.emit('error', Error(event));
          console.log('something is catching this, eating it, and causing the process to die')
        }
      });
    }).catch((err) => {
      console.log('no error here either', err);
    }).then(null, (err) => {
      console.log('no error here', err);
    });

  }
}

process.on('uncaughtException', function (exception) {
  console.log('no uncaught exception', exception);
});

process.on('unhandledRejection', (reason, p) => {
  console.log('no unhandled rejection at: Promise', p, 'reason:', reason);
});

new Wat();
```
Is there a particular way these errors need to be thrown/emitted/captured and re-throw/emitted?

**Comment by mateodelnorte** [comment]
Any ideas on this?

**Comment by cressie176** [comment]
Hi @mateodelnorte, I haven't used the promise based api, but am wondering what happens if you listen for `conn.on('error')`  or `process.on('error')`?

**Comment by mateodelnorte** [comment]
It catches the errors, for instance allowing me to log the error, but the process still dies immediately after. 

https://github.com/mateodelnorte/servicebus/blob/master/bus/rabbitmq/bus.js#L50-L51

https://github.com/mateodelnorte/servicebus/issues/93

**Comment by cressie176** [comment]
Are you sure that it's the same error? Maybe the first one is being logged then swallowed, but a second error event being emitted from something other than the connection? Does `process.on('error')` give any clues?

**Comment by mateodelnorte** [comment]
Adding process.on('error', ... to the code, as follows, produces the following: 
```
var amqp = require('amqplib');
var EventEmitter = require('events').EventEmitter;

amqp.connect('amqp://localhost').then(function (conn) {
  conn.on('close', function (event) {
    console.log('we get our event here', event)
    if (require('amqplib/lib/connection').isFatalError(event.Error)){
      console.log('and its fatal, but throwing seems to be swallowed - perhaps by the when.defer() promise?')
      throw new Error(event)
      console.log('something is catching this, eating it, and causing the process to die')
    }
  });
}).catch(function (err) {
  console.log('no error here either', err);
}).then(null, function(err) {
  console.log('no error here', err);
});

process.on('uncaughtException', function (exception) {
  console.log('no uncaught exception', exception);
});

process.on('unhandledRejection', (reason, p) => {
  console.log('no unhandled rejection at: Promise', p, 'reason:', reason);
});

process.on('error', (err) => {
  console.log('no unhandled error', err);
});
```
```
$ node ./test/.amqplib.js
no uncaught exception { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```
What's going on here?

Why would the error end up at `process.on('error` but not `process.on('uncaughtException`? 

How can this be handled without having to subscribe to events on process? 

If this is coming from the socket, shouln't 1) any error emitted or thrown be caught by uncaughtException and 2) purposefully caught, translated into a usable exception inside amqplib and rethrown as AMQPConnectionError or something of the sort (preferably emitted from something we have access to)?

**Comment by mateodelnorte** [comment]
It looks like this is happening because no catch/error promise handler was supplied here: 

https://github.com/squaremo/amqp.node/blob/master/channel_api.js#L6-L11

This is causing bluebird to do a `process.emit('error` as a result of the following code: 

https://github.com/petkaantonov/bluebird/blob/053d02ef3538708f3679705588d8319ca56c6b88/src/promise.js#L701
which leads to...
https://github.com/petkaantonov/bluebird/blob/053d02ef3538708f3679705588d8319ca56c6b88/src/debuggability.js#L39
which leads to...
https://github.com/petkaantonov/bluebird/blob/053d02ef3538708f3679705588d8319ca56c6b88/src/debuggability.js#L613
which leads to...
https://github.com/petkaantonov/bluebird/blob/053d02ef3538708f3679705588d8319ca56c6b88/src/debuggability.js#L192
which does a freaking `process.emit('error`. Not sure why bluebird's developers decided to do a process.emit('error instead of doing a freaking unhandledRejection of their promise. 

Will a `.catch` at https://github.com/squaremo/amqp.node/blob/master/channel_api.js#L6-L11 fix the problem?

**Comment by mateodelnorte** [comment]
Scratch my previous two comments. Did some testing and they're wrong. This seems to be happening because nothing is handling socket events, after connect. Adding 
```javascript
  sock.on('error', (err) => {
    console.log('yup, socket error: ', err)
  })
```
to line https://github.com/squaremo/amqp.node/blob/master/lib/connect.js#L185 will cause the following behavior: 
```
$ node ./test/.amqplib.js
yup, socket error:  { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
no uncaught exception { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
yup, socket error:  Error: This socket is closed
    at Socket._writeGeneric (net.js:680:19)
    at Socket._write (net.js:731:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:658:40)
    at Connection.C.sendBytes (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:517:15)
    at Connection.C.sendHeartbeat (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:521:15)
    at Heart.<anonymous> (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:431:12)
    at emitNone (events.js:86:13)
yup, socket error:  Error: This socket is closed
    at Socket._writeGeneric (net.js:680:19)
    at Socket._write (net.js:731:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:658:40)
    at Connection.C.sendBytes (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:517:15)
    at Connection.C.sendHeartbeat (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:521:15)
    at Heart.<anonymous> (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:431:12)
    at emitNone (events.js:86:13)
no uncaught exception Error: Heartbeat timeout
    at Heart.<anonymous> (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:425:19)
    at emitNone (events.js:86:13)
    at Heart.emit (events.js:185:7)
    at Heart.runHeartbeat (C:\development\ged\message-bus\node_modules\amqplib\lib\heartbeat.js:88:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
yup, socket error:  Error: This socket is closed
    at Socket._writeGeneric (net.js:680:19)
    at Socket._write (net.js:731:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:658:40)
    at Connection.C.sendBytes (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:517:15)
    at Connection.C.sendHeartbeat (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:521:15)
    at Heart.<anonymous> (C:\development\ged\message-bus\node_modules\amqplib\lib\connection.js:431:12)
    at emitNone (events.js:86:13)
```
So, I think this is a combination of 1) the socket error is not being handled and rethrown as something recoverable from within amqplib and 2) it's being passed to openCallback which ends up returning to a previously resolved promise, which makes bluebird in turn do a `process.emit(err` - which I've never seen anyone do EVER. lol

**Comment by mateodelnorte** [comment]
Seems this issue is the same as https://github.com/squaremo/amqp.node/issues/338.

**Comment by Lawrence-Windsor** [comment]
Did this issue ever get a solution, i am facing it as of 8th March 2019?

**Comment by PavithranRick** [comment]
Any updates on this issue please? 

`

July 6th 2019, 08:32:14.791 | Error: Heartbeat timeout | prod-svc-31
-- | -- | --
  | July 6th 2019, 08:32:14.791 | at Heart.<anonymous> (/opt/services/dev/builds/order-service/v3.890.7/node_modules/amqplib/lib/connection.js:426:19) | prod-svc-31

  | July 6th 2019, 08:32:14.791 | at emitNone (events.js:86:13) | prod-svc-31

  | July 6th 2019, 08:32:14.791 | at Heart.emit (events.js:185:7) | prod-svc-31

  | July 6th 2019, 08:32:14.791 | at Heart.runHeartbeat (/opt/services/dev/builds/order-service/v3.890.7/node_modules/amqplib/lib/heartbeat.js:88:17) | prod-svc-31
  | July 6th 2019, 08:32:14.791 | at ontimeout (timers.js:386:11) | prod-svc-31

  | July 6th 2019, 08:32:14.791 | at tryOnTimeout (timers.js:250:5) | prod-svc-31

  | July 6th 2019, 08:32:14.791 | at Timer.listOnTimeout (timers.js:214:5)

`

**Comment by cressie176** [comment]
I can reproduce with the following script...

```js
const amqplib = require('amqplib');

(async () => {
  // Heartbeat effectively disabled while due to use of debugger
  const connection = await amqplib.connect('amqp://localhost:5672?heartbeat=100000')
  connection.on('close', async () => {
    throw new Error('Oh Noes!')
  });
})();
```

If I allow the script to connect, then restart the docker container hosting the RabbitMQ server, the connection emits a close event. If the handler throws an error, this is caught in amqplib's [accept loop](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L489) and emitted as a frameError, the [event listener](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L281) for which delegates to the [onSocketError handler](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L356-L365) handler, however because [toClosed](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L95) was called when the server sent the Close command, [expectSocketClose](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L357) is true and the onSocketHandler falls through without emitting an error.

**Comment by cressie176** [comment]
A workaround is to put any code inside the close event handler within a try catch
```js
(async () => {
  const connection = await amqplib.connect('amqp://localhost:5672?heartbeat=100000')
  connection.on('close', async (err) => {
    try {
      console.log('Connection error', err)
      throw new Error('Oh Noes!')
    } catch (err) {
      console.log('Error in close handler', err);
    }
  });
})();

```

or with a setImmediate timer, e.g.

```js
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://localhost:5672?heartbeat=100000')
  connection.on('close', (err) => {
    setImmediate(() => {
      console.log('Connection error', err)    
      throw new Error('Oh Noes!')
    })
  });
})();
```
or to use the `async` keyword 
```js
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://localhost:5672?heartbeat=100000')
  connection.on('close', async (err) => {
    console.log('Connection error', err)
    throw new Error('Oh Noes!')
  });
})();
```
The former can be caught by listening for the process 'uncaughtException' event and the latter by the process 'unhandledRejection' event

**Comment by cressie176** [comment]
Labelling as a bug as amqplib should not be swallowing exceptions.

**Comment by cressie176** [comment]
I can only think of two (unsatisfactory) ways to address this

1. Change any amqplib code which emits an event (e.g. error, close, blocked, etc) that can be handled by the user code to do so from a setImmediate function so that user errors automatically bypass amqplib code
2.  Change any amqplib code which emits an event (e.g. error, close, blocked, etc) that can be handled by the user code to do so within a try/catch block, then find a way to rethrow such errors anywhere they are caught by amqplib

These would only be catchable via the process.on('uncaughtException') event, and not very useful for automated recovery, but would at least flag the error to the user rather than in the above case, causing it to be completely swallowed

A weaker alternative is to update the documentation to clearly state that any event handler code must not emit synchronous errors.

Any thoughts @kibertoad?

**Comment by kibertoad** [comment]
@cressie176 Maybe we can allow registering some kind of an error handler that we would use for publishing these errors?

**Comment by cressie176** [comment]
Yes, that's possible. It would mean wrapping each emit call within a try/catch block, e.g.

```js
try {
  this.connection.emit('close');
} catch (error) {
  this.connection.emit('handler_error', error);
}
```

but does beg the question, what would we do if the `handler_error` handler failed.

Also it might cause confusion, because try/catch would only work for synchronous errors.

**Comment by kibertoad** [comment]
`but does beg the question, what would we do if the handler_error handler failed.`

handler_error would be handled purely in userspace, right? In that case I would argue that it's on a user to handle errors correctly.

What would happen in case of asynchronous errors? Can you give an example code of how that would look?

**Comment by cressie176** [comment]
> handler_error would be handled purely in userspace, right? In that case I would argue that it's on a user to handle errors correctly.

Yes, but so is the connection close event handler. I agree it would be reasonable to require that userspace handlers do not throw exceptions from synchronous code; there is not much amqplib can do to handle them, and throwing them may interfere with its internal workings. If we take this approach then I suggest updating the docs to make the requirement explicit and close the issue issue. 

My only concern with the above is that some users won't adhere to this even if documented, and it's not great that amqplib swallows errors. 

> What would happen in case of asynchronous errors? Can you give an example code of how that would look?

#### Synchronous
```js
connection.on('close', () => {
  reconnect();
});
```

#### Asynchronous
```js
connection.on('close', () => {
  setTimeout(() => reconnect(), 1000);
});
```

In the synchronous example, if the reconnect function throws an error before becoming asynchronous, the error will be caught in amqplib's accept loop, misinterpreted as a frame error and swallowed.

In the asynchronous example, if the reconnect function throws an error, the error will bypass amqplib entirely because the handler immediately went asynchronous through the setTimeout. As a result the error will likely crash the application but at least it would be reported. 

We can enforce this behaviour by emitting events from a `setImmediate` function. e.g.
```js
setImmediate(() => this.connection.emit('close')
```
However, emitting errors asynchronously will mean that the handlers execute slightly later than they do now, which may result in some unexpected behaviour. I also haven't checked whether amqplib ever listens to its own connection close/error events. If it does, then we may also find subtle behaviour changes.

**Comment by cressie176** [comment]
### Update

When a user-supplied event handler (e.g. `connection.on('close', ...)`) threw a synchronous error, it propagated up through amqplib's internal event dispatch machinery with two bad outcomes depending on where in the call stack the throw escaped:

1. **Silently swallowed** — a throw from a `connection` `close` handler escaped into `acceptLoop`'s try/catch while `expectSocketClose` was already true (connection already closing), so it was routed through `frameError` → `onSocketError` and discarded.
2. **Connection or channel unnecessarily closed** — a throw from any other handler (e.g. `channel.on('ack', ...)`, `connection.on('blocked', ...)`) escaped into `acceptLoop`'s try/catch while the connection was still open, causing `onSocketError` to close it.

### Solution

A new `safeEmit(emitter, event, ...args)` helper wraps `emitter.emit()` in a try/catch. If the handler throws:

- If the emitter has a `handler-error` listener → fires `emitter.emit('handler-error', e)` via `setImmediate` (async, prevents re-entry into amqplib internals)
- If no `handler-error` listener → re-throws, preserving existing behaviour exactly

`safeEmit` is applied to all user-facing event emissions on both `Connection` and `Channel`.

### Usage

```js
const connection = await amqp.connect('amqp://localhost');

connection.on('handler-error', (err) => {
  // err is the error thrown by one of your connection event handlers
  console.error('Connection event handler threw:', err);
});

const channel = await connection.createChannel();

channel.on('handler-error', (err) => {
  // err is the error thrown by one of your channel event handlers
  console.error('Channel event handler threw:', err);
});
```

The fix is **opt-in and non-breaking**: if you don't add a `handler-error` listener, behaviour is unchanged from previous versions.
