### ISSUE TITLE
load balanced SSL host not working Unhandled rejection Error: socket hang up

### ISSUE THREAD

**Issue by kmacpher67** [squaremo/amqp.node#362]
Client: 
node --version  =  v4.6.0
  "name": "amqplib",  "version": "0.5.1",
 Ubuntu / Mac O/S (tested both)
Server: 
RabbitMQ 3.6.6, Erlang 19.2
O/S: Ubuntu server 14.04 debian Linux 4.4.0-59-generic

Is there a method to ignore SSL errors connection like maybe: ` process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` ? 
How do we handle a bogus self signed cert, tried adding it to opts string and passing it in? We are just looking to do SSL encrypted tunnel. 
Is there any known problems with the load balanced + SSL Configuration? 
``` 
var opts = {
    ca: [fs.readFileSync('./rmqlog-cert.pem')]
};
```
On this step with or without `, opts` we get an error: 
`var connection = amqp.connect(RABBIT_URL, opts);` 
The error is: 
``` Unhandled rejection Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1054:19)
    at TLSSocket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
``` 
The server guys are saying there are no messages on the server side other than: snippet from log: 
```
=INFO REPORT==== 27-Jun-2017::18:00:50 ===
accepting AMQP connection <0.9478.0> (10.57.102.140:19109 -> 10.57.100.180:5671)
=WARNING REPORT==== 27-Jun-2017::18:01:49 ===
closing AMQP connection <0.9478.0> (10.57.102.140:19109 -> 10.57.100.180:5671):
client unexpectedly closed TCP connection```

**Comment by kmacpher67** [comment]
this is a generic message for any time there is a socket, bad connection.  The network was hosed. 
:)
