### ISSUE TITLE
ECONNRESET after upgrading to 0.5.2

### ISSUE THREAD

**Issue by furstenheim** [squaremo/amqp.node#420]
After upgrading to 0.5.2 I'm getting some econnreset in rabbit

In the rabbit logs:

=WARNING REPORT====
closing AMQP connection ..
connection_closed_abruptly

And on the node side

Error: read ECONNRESET
      at exports._errnoException (util.js:1050:11)
      at TCP.onread (net.js:582:26)

I'll investigate further. Could it be related to https://github.com/squaremo/amqp.node/pull/340

**Comment by furstenheim** [comment]
The error was not related to the update. Possibly there is a global error that is crashing the server and that produces the log in rabbit, not the other way around
