### ISSUE TITLE
Error closing a channel

### ISSUE THREAD

**Issue by dsinecos** [squaremo/amqp.node#427]
When I close the channel in the following code

```
var amqp = require('amqplib');

async function main() {

    var connection = await amqp.connect('amqp://localhost');

    connection.on('close', () => {
        console.log("Connection closed");
    })

    var channel = await connection.createChannel();
    var queueName = 'streamPublish';
    var queue = channel.assertQueue('streamPublish', { durable: false });

    var i = 0;
    var max = 100;

    while (i < max) {

        await channel.sendToQueue(queueName, new Buffer('Hello World!'));
        i++;

        if (i === (max)) {
            close();
            // setTimeout(close, 1000);
        }
    }

    async function close() {

        console.log("Closing channel");
        await channel.close()
        console.log("Closing connection");
        await connection.close();

    }

}

process.on('unhandledRejection', (p, e) => {
    console.log("Unhandled rejection");
    console.log(p, e);
});

main();

```

I get the following error

```
Closing channel
Closing connection
Connection closed
Unhandled rejection
{ Error: Channel ended, no reply will be forthcoming
    at rej (/home/divyanshu/programming/blue-rabbit/node_modules/amqplib/lib/channel.js:190:7)
    at Channel.C._rejectPending (/home/divyanshu/programming/blue-rabbit/node_modules/amqplib/lib/channel.js:192:28)
    at Channel.C.toClosed (/home/divyanshu/programming/blue-rabbit/node_modules/amqplib/lib/channel.js:160:8)
    at Channel.accept (/home/divyanshu/programming/blue-rabbit/node_modules/amqplib/lib/channel.js:179:12)
    at Connection.mainAccept [as accept] (/home/divyanshu/programming/blue-rabbit/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/home/divyanshu/programming/blue-rabbit/node_modules/amqplib/lib/connection.js:477:48)
    at Socket.emit (events.js:127:13)
    at emitReadable_ (_stream_readable.js:520:10)
    at emitReadable (_stream_readable.js:514:7)
    at addChunk (_stream_readable.js:280:7)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:590:20)
```

However when I close the channel and the connection after a timeout like in the following code
```
var amqp = require('amqplib');

async function main() {

    var connection = await amqp.connect('amqp://localhost');

    connection.on('close', () => {
        console.log("Connection closed");
    })

    var channel = await connection.createChannel();
    var queueName = 'streamPublish';
    var queue = channel.assertQueue('streamPublish', { durable: false });

    var i = 0;
    var max = 100;

    while (i < max) {

        await channel.sendToQueue(queueName, new Buffer('Hello World!'));
        i++;

        if (i === (max)) {
            // close();
            setTimeout(close, 1000);
        }
    }

    async function close() {

        console.log("Closing channel");
        await channel.close()
        console.log("Closing connection");
        await connection.close();

    }

}

process.on('unhandledRejection', (p, e) => {
    console.log("Unhandled rejection");
    console.log(p, e);
});

main();
```

I get the following output and the channel and connection is closed without any errors
```
Closing channel
Closing connection
Connection closed
```

I am not able to understand why is there an error in the first case but not the second. Any suggestions or ideas would be of help. Thank you

**Comment by squaremo** [comment]
You don't await the return value of `channel.assertQueue(...)`, and `channel.sendToQueue(...)` does not return a promise, so what I suspect is your code runs through to the `close()` invocations before it's had a chance to send anything over the socket.
The `close` frames aren't buffered, so `channel.close()` probably ends up being sent before anything else.

To fix it, you need to await the result of assertQueue().

**Comment by dsinecos** [comment]
Thanks @squaremo Problem solved :)
