### ISSUE TITLE
Using Promises connect function won't show me the error

### ISSUE THREAD

**Issue by gustavoca** [squaremo/amqp.node#460]
Hello, i've come across something interesting:

for:

```
const amqp = require('amqplib/callback_api');
amqp.connect('', (err, conn) => {
  if (err) console.log("Error! ", err);
});

```

This will show me the expected error: 

```
Error!  { Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }
```

However doing it with Promises:

```
const amqp = require('amqplib/callback_api');
amqp.connect('')
  .then((conn) => {
    console.log('Successfully connected to RabbitMQ')
  })
  .catch((err) => {
    console.log(err)
  });
```

i get:

```
/Users/gustavo/workspace/nobelbiz-projects/smrt-service-agent-manager/test.rabbit.promises.js:3
  .then((conn) => {
  ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/Users/gustavo/workspace/nobelbiz-projects/smrt-service-agent-manager/test.rabbit.promises.js:3:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by lipho** [comment]
Looks like you're doing `const amqp = require('amqplib/callback_api');` for the promise part. Change that to `const amqp = require('amqplib');`
