### ISSUE TITLE
Error: Cannot find module './defs'

### ISSUE THREAD

**Issue by windofwind** [squaremo/amqp.node#465]
Hello! 

npm i "https://github.com/squaremo/amqp.node.git#master"
I downloaded it via this url to use amqplain. 
However, the following error occurs.

Error: Cannot find module './defs'
module.js:548
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/wind/project/test/amqptest/node_modules/amqplib/lib/connection.js:7:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by windofwind** [comment]
sorry 

"mkdir ./node_module/amqplib/bin"
"touch generate-defs.js"

"https://github.com/squaremo/amqp.node/blob/master/bin/generate-defs.js" copy and this src paste
