### ISSUE TITLE
ERR_SERVER_ALREADY_LISTEN error after Unexpected close 

### ISSUE THREAD

**Issue by s888** [squaremo/amqp.node#485]
Hi,
I am struggling with the problem and not able to find the reason for this.
In one my apps rabbitmq had Unexpected close error and when the connection was re-initiated it started giving ERR_SERVER_ALREADY_LISTEN error.

Here's the error log:
`05-01 03:44:40.195: amqperror Error: Unexpected close
05-01 03:44:40.195:     at succeed (/home/user/node_modules/amqplib/lib/connection.js:271:13)
05-01 03:44:40.195:     at onOpenOk (/home/user/node_modules/amqplib/lib/connection.js:253:5)
05-01 03:44:40.195:     at /home/user/node_modules/amqplib/lib/connection.js:166:32
05-01 03:44:40.195:     at /home/user/node_modules/amqplib/lib/connection.js:160:12
05-01 03:44:40.195:     at Socket.recv (/home/user/node_modules/amqplib/lib/connection.js:498:12)
05-01 03:44:40.195:     at Object.onceWrapper (events.js:273:13)
05-01 03:44:40.195:     at Socket.emit (events.js:182:13)
05-01 03:44:40.195:     at Socket.EventEmitter.emit (domain.js:442:20)
05-01 03:44:40.195:     at emitReadable_ (_stream_readable.js:534:12)
05-01 03:44:40.195:     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
05-01 03:44:40.195:     at process._tickCallback (internal/process/next_tick.js:63:19)
05-01 03:44:40.195: connect
05-01 03:44:40.280: connectCb
05-01 03:44:40.289: amqperror Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
05-01 03:44:40.289:     at Server.listen (net.js:1372:11)
05-01 03:44:40.289:     at Server.listen (/home/user/node_modules/restify/lib/server.js:293:31)
05-01 03:44:40.289:     at /home/user/project/services/api.js:46:12
05-01 03:44:40.289:     at /home/user/project/routes/apiHandler.js:110:9
05-01 03:44:40.289:     at /home/user/project/utils/amqpConnector.js:80:10
05-01 03:44:40.289:     at /home/user/node_modules/amqplib/lib/callback_model.js:59:7
05-01 03:44:40.289:     at /home/user/node_modules/amqplib/lib/callback_model.js:74:5
05-01 03:44:40.289:     at reply (/home/user/node_modules/amqplib/lib/channel.js:100:16)
05-01 03:44:40.289:     at ConfirmChannel.C.accept (/home/user/node_modules/amqplib/lib/channel.js:433:12)
05-01 03:44:40.289:     at Connection.mainAccept [as accept] (/home/user/node_modules/amqplib/lib/connection.js:64:33)
05-01 03:44:40.289:     at Socket.go (/home/user/node_modules/amqplib/lib/connection.js:477:48)
05-01 03:44:40.289:     at Socket.emit (events.js:182:13)
05-01 03:44:40.289:     at Socket.EventEmitter.emit (domain.js:442:20)
`
How to fix this?

**Comment by squaremo** [comment]
This looks like two errors: first, the connection closes (possibly while being established); then, after a connection is opened successfully, the restify library throws an exception in the callback of opening a channel.

From the ordering it seems there's some kind of retry code -- when the first connection closes, it tries opening another, and succeeds, leading to the second error. You will always get the occasional connection drop, so retries are a good tactic, but you have to clean up after each. I suggest installing an `'error'` handler on the connection that closes the restify listener.

**Comment by s888** [comment]
Hi,
Thank you for the response.
Are you referring to the error event of amqp lib?
The connection is re-initiated only when there is an error event in the amqp lib.
Also, this error occurred several hours after the connection was established.
Here's the re-connect code.

var amqp_cb_api = require('amqplib/callback_api');
AmqpConnector.prototype.connect = function(cb){
	console.log("connect");
	var self = this;
    amqp_cb_api.connect(config.amqp.uri, function(err, connection) {
        console.log("connectCb");
        if (err != null) {
        	bail(err);
            cb(err, null);
            return;
        }
        self.conn = connection;
    	self.conn.on('error', function(e){
            //from this error the connection is re-initiated
            //but in case of "unexpected close" error it gives  ERR_SERVER_ALREADY_LISTEN Error
            console.log("amqperror",e);
    	    self.connect(cb);
        })
        cb(null, connection);
    });
}

**Comment by cressie176** [comment]
I'm suspicious that the same callback `cb` will be called multiple times. The first time after successful or unsuccessful connection, then subsequently whenever the connection event emits an error.

**Comment by s888** [comment]
Hi,
Thank you for the response.
The code works fine when there is a heartbeat timeout error.
But in case of unexpected close error it gave this error.
Is there is method to check if the connection is closed and to close the connection?
If so, in case of error events I will check if the connection is actually closed. If it is not closed then close the connection and then re-initiate it.

**Comment by cressie176** [comment]
What's odd though is that it should be (and is) possible to have multiple connections at a time - For example I believe you need multiple if you connect to different vhosts. Therefore reconnecting should give you a new connection and the server should be fine with it.

**Comment by s888** [comment]
So when does the ERR_SERVER_ALREADY_LISTEN error actually occur?
Is there any use case where I can reproduce this error?
I searched the doc but I am not able to find any clue :(

**Comment by lightning003** [comment]
@s888  .. Were you able to fix that issue? I am seeing this issue every now and then.
Any help is appreciated

**Comment by cressie176** [comment]
ERR_SERVER_ALREADY_LISTEN doesn't appear in the ampqlib code base, however it is thrown from node's [server.listen](https://nodejs.org/api/net.html#serverlisten). amqplib does not call server.listen, so strongly suspect the above issue is down to a bug in the client application, possibly due to the previously mentioned callback being executed repeatedly. My guess is that the callback is invoking server.listen and hence getting the error the second time around.

Closing due to age.
