### ISSUE TITLE
Illegal Operation

### ISSUE THREAD

**Issue by tsgautier** [squaremo/amqp.node#51]
I'm getting Illegal Operation errors quite often under actual usage.

How can I track down who's at fault?  It's hard to tell if this is this Rabbit....amqplib or my own code.

**Comment by GavinDmello** [comment]
I'm getting this issue 
Here's the stack trace.
```
    at ConfirmChannel. (/home/code/node_modules/amqplib/lib/channel.js:149:11)
    at ConfirmChannel.Channel.publish (/home/code/node_modules/amqplib/lib/callback_model.js:171:17)
    at ConfirmChannel.publish (/home/code/node_modules/amqplib/lib/callback_model.js:301:36)
```  
I guess its because I'm publishing to a closed channel. Is there a way I can figure out why my channels are closing abruptly ?

**Comment by zenymax** [comment]
Recently I 'm getting this issue too.
production APP [9:34 PM] 
IllegalOperationError: Channel closed
    at Channel.<anonymous> (/usr/src/app/node_modules/amqplib/lib/channel.js:149:11)
    at Channel.C._rpc (/usr/src/app/node_modules/amqplib/lib/channel.js:131:8)
    at Channel.rpc (/usr/src/app/node_modules/amqplib/lib/callback_model.js:73:8)
    at Channel.assertQueue (/usr/src/app/node_modules/amqplib/lib/callback_model.js:96:15)
    at sendResultBack

we just restarted the server a couple days and it happened. Don't know why but we have a backup plan to reconnect it. To open a connection to a channel too long. is it the good solution to do that? please give me the advice. Thanks

**Comment by michaelklishin** [comment]
Restarting RabbitMQ will close all connections and thus channels. Since using closed channels makes no sense, this client throws an illegal state exception. Your code must be prepared to recover connection and channels as needed.

**Comment by neilpalima** [comment]
How to handle this `UnhandledPromiseRejectionWarning: IllegalOperationError: Channel closed`?

**Comment by neilpalima** [comment]
Not a missing catch since all block is inside a try catch. It was a missing rejection when connection emits an error/close.

**Comment by chdanielmueller** [comment]
@neilpalima Have you found a solution to this issue?

**Comment by slicerahul** [comment]
What could be the reason of this?

**Comment by cressie176** [comment]
> What could be the reason of this?

https://github.com/squaremo/amqp.node/issues/51#issuecomment-40001492

**Comment by neilpalima** [comment]
@chdanielmueller we double check if we are using existing queue s/exchanges. We also use this [package](https://www.npmjs.com/package/amqp-connection-manager) to handle auto reconnection.

**Comment by brt-han-mai** [comment]
I got this
```(node:11284) UnhandledPromiseRejectionWarning: IllegalOperationError: Channel closing
    at Channel.<anonymous> (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel.js:160:11)
    at Channel.C.closeBecause (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel.js:212:8)
    at C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel_model.js:78:17
    at tryCatcher (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\bluebird\js\release\promise.js:209:30)     
    at Channel.C.close (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel_model.js:77:18)
    at NotificationConsumer.<anonymous> (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:49:36)
    at Generator.next (<anonymous>)
    at C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:4:12)
    at NotificationConsumer.close (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:47:16)
    at NotificationServer.<anonymous> (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_server\src\NotificationServer.ts:59:41)
    at Generator.next (<anonymous>)
    at C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_server\src\NotificationServer.ts:8:71
(node:11284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 65)

han.mai@SG-PC-034 MINGW64 ~/Desktop/work/BT_SW_000025/Trunk/Notification/notification_server   
$ npm start

> notification_server@1.0.0 start C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_server
> npm run lint && ts-node src/index.ts


> notification_server@1.0.0 lint C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_server
> tslint -c tslint.json -p tsconfig.json

Example notification application
Type <CTRL + C> to exit

PRODUCER SEND: Hello World
NOTIFICATION RECEIVED: {
  from: 'system_event',
  to: [ 'user-id' ],
  type: 1,
  data: 'Hello World'
}
Goodbye!
(node:11284) UnhandledPromiseRejectionWarning: IllegalOperationError: Channel closing
    at Channel.<anonymous> (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel.js:160:11)
    at Channel.C.closeBecause (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel.js:212:8)
    at C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel_model.js:78:17
    at tryCatcher (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\bluebird\js\release\promise.js:209:30)     
    at Channel.C.close (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\node_modules\amqplib\lib\channel_model.js:77:18)
    at NotificationConsumer.<anonymous> (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:49:36)
    at Generator.next (<anonymous>)
    at C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:4:12)
    at NotificationConsumer.close (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_api\build\ClientBasic.js:47:16)
    at NotificationServer.<anonymous> (C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_server\src\NotificationServer.ts:59:41)
    at Generator.next (<anonymous>)
    at C:\Users\han.mai\Desktop\work\BT_SW_000025\Trunk\Notification\notification_server\src\NotificationServer.ts:8:71
Goodbye!
(node:11284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 66)
```

**Comment by lavket-darwin** [comment]
@cressie176 @squaremo - We are facing the same issue. We are trying to publish a message when the channel is closed. How can we prevent this ? This error is not frequent. 

Here's the complete log along with stackAtStateChange. Can you guys please suggest a fix for this?

IllegalOperationError: Channel closed
an error in sending message to RMQ, retrying...
    at Channel.<anonymous> (/data/node_modules/amqplib/lib/channel.js:160:11)
    at Channel.C._rpc (/data/node_modules/amqplib/lib/channel.js:142:8)
    at /data/node_modules/amqplib/lib/channel_model.js:59:17
    at tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/data/node_modules/bluebird/js/release/promise.js:209:30)
    at Channel.C.rpc (/data/node_modules/amqplib/lib/channel_model.js:58:18)
    at Channel.C.assertQueue (/data/node_modules/amqplib/lib/channel_model.js:86:15)
    at publishTasks (/data/sourcing/publishTasks.js:12:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)
    at async processUpdateQueue (/data/sourcing/processUpdateQueues.js:26:25)
    at async request (/data/manageUpdate.js:69:17) {
  stackAtStateChange: 'Stack capture: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - Node was put into maintenance mode"\n' +
    '    at Object.accept (/data/node_modules/amqplib/lib/connection.js:90:15)\n' +
    '    at Connection.mainAccept [as accept] (/data/node_modules/amqplib/lib/connection.js:64:33)\n' +
    '    at Socket.go (/data/node_modules/amqplib/lib/connection.js:478:48)\n' +
    '    at Socket.emit (events.js:315:20)\n' +
    '    at emitReadable_ (_stream_readable.js:558:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:83:21)'
}

**Comment by cressie176** [comment]
Hi @lavket-darwin,

```js
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect();
  connection.on('error', () => console.log('Connection error'));
  connection.on('close', () => console.log('Connection close'));
  const channel = await connection.createChannel();
  channel.on('error', () => console.log('Channel error'));
  channel.on('close', () => console.log('Channel close'));

  // Kill the connection here

  setTimeout(() => {
    console.log('Sending');
    try {
      channel.publish('', 'foo', Buffer.from('foo'));
    } catch (err) {
      console.log('Publish error');
    }
  }, 10000)
})()
```

#### Output
```
% node index.js
Connection error
Channel close
Connection close
Sending
Publish error
```

Of course you still have to worry about how you restore the connection and the channel
