### ISSUE TITLE
nodejs application hangs up

### ISSUE THREAD

**Issue by nxycdl** [squaremo/amqp.node#539]
In consumer mode, when rabbitmq hangs up or the network disconnects, my nodejs program hangs up together.

Has anyone encountered this situation?
```

[Thu Sep 12 2019 16:19:44 GMT+0800 (GMT+08:00)] [graceful:worker:11708:uncaughtException] throw error 1 times
Error: Unexpected close (uncaughtException throw 1 times on pid:11708)
    at succeed (D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:272:13)
    at onOpenOk (D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:254:5)
    at D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:166:32
    at D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:160:12
    at Socket.recv (D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:499:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: Unexpected close (uncaughtException throw 1 times on pid:11708)
    at succeed (D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:272:13)
    at onOpenOk (D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:254:5)
    at D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:166:32
    at D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:160:12
    at Socket.recv (D:\project\ethblock\node_modules\_amqplib@0.5.5@amqplib\lib\connection.js:499:12)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Thu Sep 12 2019 16:19:44 GMT+0800 (GMT+08:00)] [graceful:worker:11708] will exit after 30000ms
[Thu Sep 12 2019 16:19:44 GMT+0800 (GMT+08:00)] [graceful:worker:11708] close server#0, _connections: 2
[Thu Sep 12 2019 16:19:44 GMT+0800 (GMT+08:00)] [graceful:worker:11708] close 1 servers!
[Thu Sep 12 2019 16:19:44 GMT+0800 (GMT+08:00)] [graceful:worker:11708] worker disconnect!
[2019-09-12 16:19:44.940] [cfork:master:11240] worker:11708 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2019-09-12 16:19:44.947] [cfork:master:11240] don't fork new work (refork: false)
2019-09-12 16:19:44,948 INFO 11240 [master] app_worker#1:11708 disconnect, suicide: true, state: disconnected, current workers: ["1"]
[Thu Sep 12 2019 16:20:14 GMT+0800 (GMT+08:00)] [graceful:worker:11708] kill timeout, exit now.
2019-09-12 16:20:15,307 ERROR 11708 [app_worker] exit with code:1
2019-09-12 16:20:15,313 WARN 17680 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2019-09-12 16:20:15.321] [cfork:master:11240] worker:11708 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)
```

**Comment by cressie176** [comment]
Hi @nxycdl,

I haven't experienced any problems caused by amqplib as a result of the connection being dropped. It looks like you have something intercepting uncaught exceptions (graceful?). My guess is that you haven't registered error / close handlers on the amqp connection and consequently something else is receiving them and stopping your node application from crashing, but also causing some other side effects

**Comment by cressie176** [comment]
Did you find the problem @nxycdl?

**Comment by cressie176** [comment]
Closing due to inactivity.
