### ISSUE TITLE
Error connecting to RabbitMQ

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [squaremo/amqp.node#548]
I get the following error when I try to create a connection:

```
{ Error: Socket closed abruptly during opening handshake
 at TLSSocket.endWhileOpening (/home/ubuntu/eyowo/notifications/node_modules/amqplib/lib/connection.js:260:17)
at emitNone (events.js:111:20)
at TLSSocket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickCallback (internal/process/next_tick.js:181:9)
cause: Error: Socket closed abruptly during opening handshake
at TLSSocket.endWhileOpening (/home/ubuntu/eyowo/notifications/node_modules/amqplib/lib/connection.js:260:17)
at emitNone (events.js:111:20)
at TLSSocket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickCallback (internal/process/next_tick.js:181:9),
isOperational: true }
```
*amqplib version*: 0.5.5
Node.js version: 9.9.0

**Comment by cressie176** [comment]
Hi @OpesanyaAdebayo.
Did you get this working? I strongly suspect this is caused by incorrect configuration or your environment.
