### ISSUE TITLE
async/await for channel.consume not working

### ISSUE THREAD

**Issue by AndriiNyzhnyk** [squaremo/amqp.node#577]
I am trying to implement a very simple consumer. I have noticed that "channel.consume" not working with async/await syntax.

For example: 
```js
channel.consume(targetQueue, function(msg) {
        if (msg !== null) {
             console.log(msg.content.toString());
             channel.ack(msg);
        }
});
```

working well and with async/await syntax not

```js
const message = await channel.consume(targetQueue);

 if (message !== null) {
         console.log(message.content.toString());
         channel.ack(message);
  }
```

The error
```bash
Error: Unknown consumer: amq.ctag-A4tk9j1ESF04PsI-w3_1Qw
    at Channel.BaseChannel.dispatchMessage (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/channel.js:488:11)
    at Channel.BaseChannel.handleDelivery (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/channel.js:493:15)
    at Channel.emit (events.js:315:20)
    at /home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/channel.js:279:10
    at Channel.content [as handleMessage] (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/channel.js:332:9)
    at Channel.C.acceptMessageFrame (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/channel.js:247:31)
    at Channel.C.accept (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/channel.js:400:17)
    at Connection.mainAccept [as accept] (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:556:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on ChannelModel instance at:
    at Connection.emit (events.js:315:20)
    at Connection.C.onSocketError (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/connection.js:353:10)
    at Connection.emit (events.js:315:20)
    at Socket.go (/home/andryxaua/WebstormProjects/monitoringForProjects/node_modules/amqplib/lib/connection.js:481:12)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:556:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 541
}

```

**Comment by cressie176** [comment]
Hi @AndriiNyzhnyk,

`channel.consume` doesn't just receive a single message, it sets up a permanent consumer to the queue, and will deliver multiple messages as they become available. Therefore it wouldn't make sense to return them. You need to pass a callback that will be executed multiple times as described in the [documentation](https://www.squaremobius.net/amqp.node/channel_api.html#channel_consume).

If instead you want to retrieve a single message you could look at [channel.get](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get)

**Comment by AndriiNyzhnyk** [comment]
Thanks. I have thought about it too. One additional question: why do not use event emitter for these cases? Maybe it will be more predictable. But anyway thanks for very fast response)

**Comment by cressie176** [comment]
An event emitter could have been used (I maintain a wrapper for amqplib called [Rascal](http://github.com/guidesmiths/rascal) that is event emitter based). One problem I found with this approach is that you need to register event listeners before setting up the consumer, otherwise messages will be lost. There are ways around this, but they add extra complexity.

Another reason why event emitters may have been avoided is because it implies you can register multiple listeners. While this would be possible, since a message can only be acknowledged once, this could lead to problems.

**Comment by AndriiNyzhnyk** [comment]
The last question. What do you think I should use if I want to start a new project? What will be better supported in the nearest years?

**Comment by cressie176** [comment]
amqplib has millions of downloads, and because of that is likely to be supported for as long as Node.js is popular. Because of this it's far more likely that bugs will be discovered and fixed via pull requests. In comparison, Rascal currently gets around 25K~30K downloads per month, and while it's been quite stable, the lower user base means there could be bugs lurking that I'm not aware of. I would say use either, but read both the [amqplib documentation](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get) and [Rascal's Readme](https://github.com/guidesmiths/rascal/blob/master/README.md). That should give you a good understanding of both APIs and the problems with RabbitMQ I was trying to solve when writing Rascal.

**Comment by AndriiNyzhnyk** [comment]
Thank you so much
